// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Core.Data;

#nullable disable

namespace Server.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001195254_AddResourceTemplateDescription")]
    partial class AddResourceTemplateDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Domain.CalendarFeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("availability");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<Guid>("ShareToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.HasIndex("SpaceId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CalendarFeeds", t =>
                        {
                            t.HasCheckConstraint("CK_CalendarFeeds_Display", "[DisplayMode] IN ('availability', 'titles', 'details')");

                            t.HasCheckConstraint("CK_CalendarFeeds_ResourceTeam", "[ResourceId] IS NULL OR [TeamId] IS NOT NULL");

                            t.HasCheckConstraint("CK_CalendarFeeds_Scope", "([SpaceId] IS NOT NULL AND [ResourceId] IS NULL) OR ([SpaceId] IS NULL AND [ResourceId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.CatalogFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SpaceId")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SpaceId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("Files", t =>
                        {
                            t.HasCheckConstraint("CK_Files_OneOwner", "(SpaceId IS NOT NULL AND ResourceId IS NULL) OR (SpaceId IS NULL AND ResourceId IS NOT NULL)");

                            t.HasCheckConstraint("CK_Files_Size", "SizeBytes >= 0");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.Person", b =>
                {
                    b.Property<string>("IamId")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<DateTime?>("FirstIngestedAt")
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActiveInIam")
                        .HasColumnType("bit");

                    b.Property<string>("IsCampusEmployee")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<bool?>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFaculty")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHsEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStaff")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStudent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastRunId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("ModifyDateRaw")
                        .HasMaxLength(19)
                        .HasColumnType("char(19)");

                    b.Property<string>("PrivacyCode")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("datetime2(6)");

                    b.Property<string>("PromotionRunId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEndpoint")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(9)
                        .HasColumnType("char(9)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("UserId")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.HasKey("IamId")
                        .HasName("PK_People");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IamId"));

                    b.ToTable("People");
                });

            modelBuilder.Entity("Server.Core.Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("BillingAttentionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("BillingAttentionRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("BillingDispatchStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("BillingDueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("BillingPreparedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BillingSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("waiting");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OccurrenceNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentsInvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentsLinkId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentsStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("PaymentsSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReservationSeriesId")
                        .HasColumnType("int");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("ShareToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("PaymentsInvoiceId")
                        .IsUnique()
                        .HasFilter("[PaymentsInvoiceId] IS NOT NULL");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("[ShareToken] IS NOT NULL");

                    b.HasIndex("BillingStatus", "BillingDueAt");

                    b.HasIndex("ReservationSeriesId", "OccurrenceNumber")
                        .IsUnique();

                    b.HasIndex("Status", "StartsAt");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_Attention", "[BillingStatus] <> 'needs_attention' OR ([BillingAttentionRequired] = 1 AND [BillingAttentionNote] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Reservations_BillingStatus", "[BillingStatus] IN ('waiting', 'prepared', 'submitting', 'linked', 'free', 'skipped', 'needs_attention')");

                            t.HasCheckConstraint("CK_Reservations_Calculation", "([BillingPreparedAt] IS NULL AND [Amount] IS NULL AND [BillingSnapshotJson] IS NULL) OR ([BillingPreparedAt] IS NOT NULL AND [Amount] IS NOT NULL AND [Amount] >= 0 AND [BillingSnapshotJson] IS NOT NULL AND ISJSON([BillingSnapshotJson]) = 1)");

                            t.HasCheckConstraint("CK_Reservations_Dispatched", "[BillingDispatchStartedAt] IS NULL OR ([BillingPreparedAt] IS NOT NULL AND [Amount] > 0)");

                            t.HasCheckConstraint("CK_Reservations_ExternalInvoice", "[PaymentsInvoiceId] IS NULL OR [BillingDispatchStartedAt] IS NOT NULL");

                            t.HasCheckConstraint("CK_Reservations_Free", "[BillingStatus] <> 'free' OR ([BillingPreparedAt] IS NOT NULL AND [Amount] = 0 AND [BillingDispatchStartedAt] IS NULL AND [PaymentsInvoiceId] IS NULL)");

                            t.HasCheckConstraint("CK_Reservations_Interval", "[OccurrenceNumber] > 0 AND [Revision] > 0 AND [EndsAt] > [StartsAt]");

                            t.HasCheckConstraint("CK_Reservations_Linked", "[BillingStatus] <> 'linked' OR ([PaymentsInvoiceId] IS NOT NULL AND [PaymentsLinkId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Reservations_Prepared", "[BillingStatus] <> 'prepared' OR ([BillingPreparedAt] IS NOT NULL AND [Amount] > 0 AND [BillingDispatchStartedAt] IS NULL AND [PaymentsInvoiceId] IS NULL)");

                            t.HasCheckConstraint("CK_Reservations_Status", "[Status] IN ('pending', 'approved', 'rejected', 'canceled')");

                            t.HasCheckConstraint("CK_Reservations_Submitting", "[BillingStatus] NOT IN ('submitting', 'linked') OR [BillingDispatchStartedAt] IS NOT NULL");

                            t.HasCheckConstraint("CK_Reservations_Unprepared", "[BillingStatus] NOT IN ('waiting', 'skipped') OR ([BillingPreparedAt] IS NULL AND [BillingDispatchStartedAt] IS NULL AND [PaymentsInvoiceId] IS NULL)");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.ReservationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationRevision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ReservationId", "ReservationRevision")
                        .IsUnique();

                    b.ToTable("ReservationEvents", t =>
                        {
                            t.HasCheckConstraint("CK_ReservationEvents_Details", "[ReservationRevision] > 0 AND ISJSON([DetailsJson]) = 1");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.ReservationNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationSeriesId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("ReservationSeriesId");

                    b.HasIndex("ReservationId", "ReservationSeriesId");

                    b.HasIndex("SentAt", "NextAttemptAt");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Payload", "[AttemptCount] >= 0 AND ISJSON([PayloadJson]) = 1");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.ReservationSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FormResponsesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecurrenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceConfigId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ShareToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmissionKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("[ShareToken] IS NOT NULL");

                    b.HasIndex("SubmissionKey")
                        .IsUnique();

                    b.HasIndex("RequesterUserId", "CreatedAt");

                    b.HasIndex("ResourceConfigId", "ResourceId");

                    b.HasIndex("ResourceId", "CreatedAt");

                    b.ToTable("ReservationSeries", t =>
                        {
                            t.HasCheckConstraint("CK_ReservationSeries_Recurrence", "[RecurrenceJson] IS NULL OR ISJSON([RecurrenceJson]) = 1");

                            t.HasCheckConstraint("CK_ReservationSeries_Responses", "ISJSON([FormResponsesJson]) = 1");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowReservationSharing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("manual");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FollowTeamCalendar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsReservable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentResourceId")
                        .HasColumnType("int");

                    b.Property<string>("PublicAccess")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SpaceId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentResourceId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("SpaceId", "Slug")
                        .IsUnique();

                    b.HasIndex("TeamId", "SpaceId");

                    b.HasIndex("ParentResourceId", "SpaceId", "TeamId");

                    b.HasIndex("SpaceId", "ParentResourceId", "NameKey")
                        .IsUnique();

                    b.ToTable("Resources", t =>
                        {
                            t.HasCheckConstraint("CK_Resources_Approval", "ApprovalMode IN ('automatic', 'manual')");

                            t.HasCheckConstraint("CK_Resources_Capacity", "Capacity IS NULL OR Capacity > 0");

                            t.HasCheckConstraint("CK_Resources_PublicScope", "(ParentResourceId IS NULL AND PublicAccess IS NOT NULL AND PublicAccess IN ('none', 'availability', 'details')) OR (ParentResourceId IS NOT NULL AND PublicAccess IS NULL)");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.ResourceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetailsSchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("FormJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormSchemaVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PublishedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("SourceTemplateId");

                    b.HasIndex("ResourceId", "Version")
                        .IsUnique();

                    b.ToTable("ResourceConfigs", t =>
                        {
                            t.HasCheckConstraint("CK_ResourceConfigs_Details", "DetailsSchemaVersion > 0 AND ISJSON(DetailsJson) = 1");

                            t.HasCheckConstraint("CK_ResourceConfigs_Form", "Version > 0 AND FormSchemaVersion > 0 AND ISJSON(FormJson) = 1");

                            t.HasCheckConstraint("CK_ResourceConfigs_Publication", "(PublishedAt IS NULL AND PublishedByUserId IS NULL) OR (PublishedAt IS NOT NULL AND PublishedByUserId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.ResourceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FormJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormSchemaVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResourceDefaultsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ResourceTemplates", t =>
                        {
                            t.HasCheckConstraint("CK_ResourceTemplates_Defaults", "ResourceDefaultsJson IS NULL OR ISJSON(ResourceDefaultsJson) = 1");

                            t.HasCheckConstraint("CK_ResourceTemplates_Form", "FormSchemaVersion > 0 AND ISJSON(FormJson) = 1");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.ScheduleException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("IntervalsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("manual");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ResourceId", "LocalDate")
                        .IsUnique()
                        .HasFilter("[ResourceId] IS NOT NULL");

                    b.HasIndex("TeamId", "LocalDate")
                        .IsUnique()
                        .HasFilter("[TeamId] IS NOT NULL");

                    b.ToTable("ScheduleExceptions", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduleExceptions_Intervals", "(Kind = 'closed' AND IntervalsJson IS NULL) OR (Kind = 'hours' AND ResourceId IS NOT NULL AND IntervalsJson IS NOT NULL AND ISJSON(IntervalsJson) = 1)");

                            t.HasCheckConstraint("CK_ScheduleExceptions_Kind", "Kind IN ('closed', 'hours') AND Source IN ('manual', 'holiday_import')");

                            t.HasCheckConstraint("CK_ScheduleExceptions_Scope", "(TeamId IS NOT NULL AND ResourceId IS NULL) OR (TeamId IS NULL AND ResourceId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.Space", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOfficialFacility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[IsOfficialFacility] = 1 AND [ReferenceNumber] IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Spaces", t =>
                        {
                            t.HasCheckConstraint("CK_Spaces_OfficialReference", "[IsOfficialFacility] = 0 OR [ReferenceNumber] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentsApiKeySecretName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentsTeamSlug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Server.Core.Domain.TeamPermission", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamPermissions", t =>
                        {
                            t.HasCheckConstraint("CK_TeamPermissions_Role", "[Role] IN ('admin', 'editor', 'viewer')");
                        });
                });

            modelBuilder.Entity("Server.Core.Domain.TeamSpace", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("SpaceId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "SpaceId");

                    b.HasIndex("SpaceId");

                    b.ToTable("TeamSpaces");
                });

            modelBuilder.Entity("Server.Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("IamId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IamId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Core.Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("Server.Core.Domain.CalendarFeed", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Resource");

                    b.Navigation("Space");

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Server.Core.Domain.CatalogFile", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Resource");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Server.Core.Domain.Reservation", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.ReservationSeries", "ReservationSeries")
                        .WithMany()
                        .HasForeignKey("ReservationSeriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("ReservationSeries");
                });

            modelBuilder.Entity("Server.Core.Domain.ReservationEvent", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Server.Core.Domain.ReservationNotification", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.ReservationSeries", "ReservationSeries")
                        .WithMany()
                        .HasForeignKey("ReservationSeriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId", "ReservationSeriesId")
                        .HasPrincipalKey("Id", "ReservationSeriesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RecipientUser");

                    b.Navigation("Reservation");

                    b.Navigation("ReservationSeries");
                });

            modelBuilder.Entity("Server.Core.Domain.ReservationSeries", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.User", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.ResourceConfig", "ResourceConfig")
                        .WithMany()
                        .HasForeignKey("ResourceConfigId", "ResourceId")
                        .HasPrincipalKey("Id", "ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("RequesterUser");

                    b.Navigation("Resource");

                    b.Navigation("ResourceConfig");
                });

            modelBuilder.Entity("Server.Core.Domain.Resource", b =>
                {
                    b.HasOne("Server.Core.Domain.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Resource", "ParentResource")
                        .WithMany()
                        .HasForeignKey("ParentResourceId", "SpaceId", "TeamId")
                        .HasPrincipalKey("Id", "SpaceId", "TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentResource");

                    b.Navigation("Space");

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Server.Core.Domain.ResourceConfig", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.ResourceTemplate", "SourceTemplate")
                        .WithMany()
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("PublishedByUser");

                    b.Navigation("Resource");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("Server.Core.Domain.ResourceTemplate", b =>
                {
                    b.HasOne("Server.Core.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Server.Core.Domain.ScheduleException", b =>
                {
                    b.HasOne("Server.Core.Domain.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Server.Core.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Resource");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Server.Core.Domain.TeamPermission", b =>
                {
                    b.HasOne("Server.Core.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Core.Domain.TeamSpace", b =>
                {
                    b.HasOne("Server.Core.Domain.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Server.Core.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Space");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
